import path from "node:path";
import process, { loadEnvFile } from "node:process";
import { mkdir, writeFile } from "node:fs/promises";

import { google } from "googleapis";

import {
  CATALOG_SOURCE_RANGES,
  catalogSourceTablesFromBatchGet,
} from "../src/lib/catalog/source/google-sheets";
import { loadServiceAccountCredentials } from "../src/lib/catalog/source/google-credentials";
import { buildCatalogFromTables } from "../src/lib/catalog/source/tabular";

const READONLY_SCOPE = "https://www.googleapis.com/auth/spreadsheets.readonly";

const OUTPUT_PATH = path.resolve(process.cwd(), "src/data/catalog-source.google.generated.ts");

function loadLocalEnvironment(): void {
  const envPath = path.resolve(process.cwd(), ".env.local");

  try {
    loadEnvFile(envPath);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);

    throw new Error(`Could not load local environment file "${envPath}": ${message}`);
  }
}

function requireEnvironmentVariable(name: string): string {
  const value = process.env[name]?.trim();

  if (!value) {
    throw new Error(`Missing required environment variable "${name}".`);
  }

  return value;
}

function renderGeneratedSource(source: unknown): string {
  return `/**
 * GENERATED FILE.
 * DO NOT EDIT MANUALLY.
 * Generated by scripts/sync-catalog-from-google.ts.
 */

import type { CatalogSourceTables } from "@/lib/catalog/source/types";

export const catalogSourceGoogle =
  ${JSON.stringify(source, null, 2)} as const satisfies CatalogSourceTables;
`;
}

function getGoogleApiErrorDetails(error: unknown): {
  code: number | null;
  status: string | null;
  message: string;
} {
  if (typeof error !== "object" || error === null) {
    return {
      code: null,
      status: null,
      message: String(error),
    };
  }

  const candidate = error as {
    code?: unknown;
    response?: {
      status?: unknown;
      data?: {
        error?: {
          status?: unknown;
          message?: unknown;
        };
      };
    };
    message?: unknown;
  };

  const responseError = candidate.response?.data?.error;

  return {
    code: typeof candidate.code === "number" ? candidate.code : null,

    status:
      typeof responseError?.status === "string"
        ? responseError.status
        : typeof candidate.response?.status === "number"
          ? String(candidate.response.status)
          : null,

    message:
      typeof responseError?.message === "string"
        ? responseError.message
        : typeof candidate.message === "string"
          ? candidate.message
          : String(error),
  };
}

async function main(): Promise<void> {
  loadLocalEnvironment();

  const spreadsheetId = requireEnvironmentVariable("GOOGLE_SHEETS_SPREADSHEET_ID");

  const credentialFile = requireEnvironmentVariable("GOOGLE_SERVICE_ACCOUNT_JSON_FILE");

  const credentials = await loadServiceAccountCredentials(credentialFile, process.cwd());

  console.log(`Using Google service account: ${credentials.client_email}`);

  console.log(`Using spreadsheet ID: ${spreadsheetId}`);

  const auth = new google.auth.JWT({
    email: credentials.client_email,
    key: credentials.private_key,
    scopes: [READONLY_SCOPE],
  });

  const sheets = google.sheets({
    version: "v4",
    auth,
  });

  let result;

  try {
    result = await sheets.spreadsheets.values.batchGet({
      spreadsheetId,
      ranges: CATALOG_SOURCE_RANGES,
      majorDimension: "ROWS",
      valueRenderOption: "UNFORMATTED_VALUE",
    });
  } catch (error) {
    const details = getGoogleApiErrorDetails(error);

    throw new Error(
      [
        "Google Sheets API request failed.",
        `HTTP code: ${details.code ?? "unknown"}.`,
        `Status: ${details.status ?? "unknown"}.`,
        `Message: ${details.message}`,
      ].join(" "),
    );
  }

  const source = catalogSourceTablesFromBatchGet(result.data);

  const catalog = buildCatalogFromTables(source);

  await mkdir(path.dirname(OUTPUT_PATH), {
    recursive: true,
  });

  await writeFile(OUTPUT_PATH, renderGeneratedSource(source), "utf8");

  console.log("Google Sheets catalog synchronized successfully.");

  console.log(`Brands: ${catalog.brands.length}`);

  console.log(`Categories: ${catalog.categories.length}`);

  console.log(`Products: ${catalog.products.length}`);

  console.log(`Generated source: ${OUTPUT_PATH}`);
}

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);

  console.error(`Google Sheets catalog sync failed: ${message}`);

  process.exitCode = 1;
});
