/**
 * GENERATED FILE.
 * DO NOT EDIT MANUALLY.
 * Generated by scripts/sync-catalog-from-google.ts.
 */

import type { CatalogSourceTables } from "@/lib/catalog/source/types";

export const catalogSourceGoogle =
  {
  "meta": [
    [
      "key",
      "value"
    ],
    [
      "schema_version",
      1
    ]
  ],
  "brands": [
    [
      "id",
      "slug",
      "name",
      "description",
      "logo",
      "active"
    ],
    [
      "demo-brand-a",
      "marca-demo-a",
      "Marca Demo A",
      "Marca de demostraciÃ³n para validar la estructura del catÃ¡logo.",
      "",
      true
    ],
    [
      "demo-brand-b",
      "marca-demo-b",
      "Marca Demo B",
      "Segunda marca de demostraciÃ³n para probar el catÃ¡logo multimarca.",
      "",
      true
    ]
  ],
  "categories": [
    [
      "id",
      "slug",
      "name",
      "description",
      "parent_id",
      "active"
    ],
    [
      "karategis",
      "karategis",
      "Karategis",
      "Karategis para entrenamiento y competiciÃ³n.",
      "",
      true
    ],
    [
      "protecciones",
      "protecciones",
      "Protecciones",
      "Equipamiento de protecciÃ³n para la prÃ¡ctica del Karate-Do.",
      "",
      true
    ],
    [
      "guantines",
      "guantines",
      "Guantines",
      "Guantines y protecciones para manos.",
      "protecciones",
      true
    ],
    [
      "empeineras-espinilleras",
      "empeineras-espinilleras",
      "Empeineras y espinilleras",
      "ProtecciÃ³n para pies y piernas.",
      "protecciones",
      true
    ],
    [
      "cinturones",
      "cinturones",
      "Cinturones",
      "Cinturones para la prÃ¡ctica del Karate-Do.",
      "",
      true
    ],
    [
      "accesorios",
      "accesorios",
      "Accesorios",
      "Accesorios relacionados con la prÃ¡ctica del Karate-Do.",
      "",
      true
    ]
  ],
  "products": [
    [
      "id",
      "sku",
      "slug",
      "name",
      "brand_id",
      "category_id",
      "short_description",
      "description",
      "approval",
      "approval_note",
      "availability",
      "featured",
      "active"
    ],
    [
      "demo-product-001",
      "DEMO-KARATEGI-001",
      "karategi-demo-001",
      "Karategi de demostraciÃ³n 001",
      "demo-brand-a",
      "karategis",
      "Producto de prueba para validar el modelo de datos del catÃ¡logo.",
      "Producto de demostraciÃ³n. SerÃ¡ sustituido posteriormente por informaciÃ³n comercial real.",
      "UNSPECIFIED",
      "La certificaciÃ³n se incorporarÃ¡ Ãºnicamente cuando exista informaciÃ³n verificable.",
      "CONSULT",
      true,
      true
    ],
    [
      "demo-product-002",
      "DEMO-GUANTINES-001",
      "guantines-demo-001",
      "Guantines de demostraciÃ³n 001",
      "demo-brand-b",
      "guantines",
      "Producto de prueba para validar categorÃ­as y variantes.",
      "Producto de demostraciÃ³n. No representa una oferta comercial real.",
      "UNSPECIFIED",
      "",
      "CONSULT",
      false,
      true
    ],
    [
      "demo-product-003",
      "DEMO-CINTURON-001",
      "cinturon-demo-001",
      "CinturÃ³n de demostraciÃ³n 001",
      "demo-brand-a",
      "cinturones",
      "Producto de prueba para validar filtros y categorÃ­as.",
      "Producto de demostraciÃ³n para la primera versiÃ³n tÃ©cnica del catÃ¡logo.",
      "UNSPECIFIED",
      "",
      "CONSULT",
      false,
      true
    ]
  ],
  "variants": [
    [
      "id",
      "product_id",
      "label",
      "available"
    ],
    [
      "demo-product-001-v1",
      "demo-product-001",
      "Talla de demostraciÃ³n",
      true
    ],
    [
      "demo-product-002-v1",
      "demo-product-002",
      "Rojo Â· S",
      true
    ],
    [
      "demo-product-002-v2",
      "demo-product-002",
      "Rojo Â· M",
      true
    ],
    [
      "demo-product-002-v3",
      "demo-product-002",
      "Azul Â· M",
      true
    ],
    [
      "demo-product-003-v1",
      "demo-product-003",
      "DemostraciÃ³n",
      true
    ]
  ],
  "variant_options": [
    [
      "variant_id",
      "name",
      "value",
      "sort_order"
    ],
    [
      "demo-product-001-v1",
      "Talla",
      "Demo",
      1
    ],
    [
      "demo-product-002-v1",
      "Color",
      "Rojo",
      1
    ],
    [
      "demo-product-002-v1",
      "Talla",
      "S",
      2
    ],
    [
      "demo-product-002-v2",
      "Color",
      "Rojo",
      1
    ],
    [
      "demo-product-002-v2",
      "Talla",
      "M",
      2
    ],
    [
      "demo-product-002-v3",
      "Color",
      "Azul",
      1
    ],
    [
      "demo-product-002-v3",
      "Talla",
      "M",
      2
    ],
    [
      "demo-product-003-v1",
      "PresentaciÃ³n",
      "Demo",
      1
    ]
  ],
  "prices": [
    [
      "product_id",
      "amount",
      "currency",
      "basis",
      "label",
      "note",
      "sort_order"
    ],
    [
      "demo-product-001",
      "",
      "",
      "CONSULT",
      "Consultar precio",
      "Precio pendiente de informaciÃ³n comercial real.",
      1
    ],
    [
      "demo-product-002",
      "",
      "",
      "CONSULT",
      "Consultar precio",
      "",
      1
    ],
    [
      "demo-product-003",
      "",
      "",
      "CONSULT",
      "Consultar precio",
      "",
      1
    ]
  ],
  "images": [
    [
      "product_id",
      "src",
      "alt",
      "source_type",
      "source_url",
      "sort_order"
    ]
  ],
  "features": [
    [
      "product_id",
      "feature",
      "sort_order"
    ],
    [
      "demo-product-001",
      "Modelo de demostraciÃ³n",
      1
    ],
    [
      "demo-product-001",
      "Datos preparados para variantes",
      2
    ],
    [
      "demo-product-001",
      "Sin certificaciÃ³n comercial declarada",
      3
    ],
    [
      "demo-product-002",
      "Modelo de demostraciÃ³n",
      1
    ],
    [
      "demo-product-002",
      "CategorÃ­a de protecciÃ³n",
      2
    ],
    [
      "demo-product-002",
      "Variantes preparadas para el catÃ¡logo",
      3
    ],
    [
      "demo-product-003",
      "Modelo de demostraciÃ³n",
      1
    ],
    [
      "demo-product-003",
      "Estructura preparada para variantes",
      2
    ]
  ]
} as const satisfies CatalogSourceTables;
